meta:
  environment: (( param "please set meta environment" ))
  dns_root: (( param "please set meta dns_root" ))
  security_groups: (( param "please set meta security_groups" ))
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

jobs:
  - name: vault
    instances: 1
    networks: [{name: vault1}]
    persistent_disk: (( grab meta.persistent_disk ))
  - name: broker
    instances: 1
    networks: [{name: vault1}]
  - name: sanity-test
    instances: 1
    networks: [{name: vault1}]

compilation:
  cloud_properties:
    instance_type: m3.medium

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: vault1
    type: dynamic
    cloud_properties:
      security_groups: (( grab meta.security_groups ))
