meta:
  environment: vault-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  persistent_disk: 4096

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: vault
    instances: 1
    networks:
      - name: vault1
        static_ips: (( static_ips 1 ))
    persistent_disk: (( grab meta.persistent_disk ))
    properties:
      vault:
        backend:
          use_file: true

  - name: broker
    instances: 1
    networks:
      - name: vault1
        static_ips: (( static_ips 0 ))

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: vault1
  type: manual
  subnets:
  - range: 10.244.8.0/24
    gateway: 10.244.8.1
    static:
      - 10.244.8.2 - 10.244.8.60
